name: Parse Discord Messages

on:
  schedule:
    - cron: '0 0 * * 0'    # по воскресеньям в полночь UTC
  workflow_dispatch: {}   # ручной запуск

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install discum plyvel gspread oauth2client requests

      - name: Run Discord parser
        env:
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}
          CHANNEL_IDS:        ${{ secrets.CHANNEL_IDS }}
          WEEK_DAYS:          '7'
          GOOGLE_SHEET_ID:    ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDS_JSON:  ${{ secrets.GOOGLE_CREDS_JSON }}
        run: python parse_discord.py
