name: Discord Export

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # каждый день в полночь UTC

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DiscordChatExporter CLI
        run: |
          VERSION="2.44.2"
          ASSET="DiscordChatExporter.Cli.linux-x64.zip"
          wget -qO "$ASSET" \
            "https://github.com/Tyrrrz/DiscordChatExporter/releases/download/$VERSION/$ASSET"
          unzip -q "$ASSET" -d discord-exporter
          chmod +x discord-exporter/DiscordChatExporter.Cli
          echo "$PWD/discord-exporter" >> $GITHUB_PATH

      - name: Export channels
        env:
          DC_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}  # используем токен бота
        run: |
          mkdir -p exports
          for CHANNEL in 1349119225868058644 1349121405903573114; do
            DiscordChatExporter.Cli export \\
              --output exports/channel-$CHANNEL.json
          done

      - name: Run Python parser
        env:
          DISCORD_USER_TOKEN:  ${{ secrets.DISCORD_USER_TOKEN }}
          GOOGLE_CREDS_JSON:   ${{ secrets.GOOGLE_CREDS_JSON }}
          GOOGLE_SHEET_ID:     ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          pip install plyvel gspread oauth2client
          python parse_leveldb.py

      - name: Commit and push exports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add exports/
          git commit -m "Automated Discord export"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
