name: Discord Self-Bot Export

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # каждый день в полночь UTC

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run self-bot exporter
        id: selfbot
        env:
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}
          GOOGLE_CREDS_JSON:  ${{ secrets.GOOGLE_CREDS_JSON }}
          GOOGLE_SHEET_ID:    ${{ secrets.GOOGLE_SHEET_ID }}
          CHANNEL_IDS:        ${{ secrets.CHANNEL_IDS }}  # CSV list: id,id,id...
        run: |
          echo "DEBUG: $CHANNEL_IDS"
          python -m pip install --upgrade pip
          pip install discord.py-self gspread oauth2client plyvel
          python selfbot_export.py

      - name: Commit and push exports
        if: steps.selfbot.outputs.found != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add exports/
          git commit -m "Automated Discord export via self-bot"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
