name: Discord Notify to Telegram

on:
  schedule:
    - cron: "0 * * * *"  # Каждый час (UTC)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 65

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y discord discord.py || true
          rm -rf ~/.cache/pip
          pip install git+https://github.com/dolfies/discord.py-self.git requests

      - name: Run notify script (with debug)
        env:
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scripts/notify.py
