name: Notify Discord to Telegram

on:
  schedule:
    - cron: "*/2 * * * *"  # каждые 2 минуты по UTC
  workflow_dispatch:       # позволяет запуск вручную из интерфейса GitHub

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py-self requests

      - name: Run notify script
        env:
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN2 }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID2 }}
        run: |
          python notify.py
