# name: Discord Notify All Subnets

# on:
#   schedule:
#     - cron: "0 */4 * * *"  # Каждые 4 часа
#   workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 250  # 4 часа + запас

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y discord discord.py || true
          rm -rf ~/.cache/pip
          pip install git+https://github.com/dolfies/discord.py-self.git requests

      - name: Run notify script
        env:
          DISCORD_USER_TOKEN: ${{ secrets.DISCORD_USER_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SUBNET_CONFIG_JSON: ${{ secrets.SUBNET_CONFIG_JSON }}
        run: python scripts/notify.py
